<%@ Page Title="Carrito" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Carrito.aspx.cs" Inherits="WebGalpon.Carrito" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div style="margin:50px 0 30px 0;text-align:center">
      <asp:Label runat="server" ID="TitleLabel"></asp:Label>
      
    <asp:Label runat="server" ID="AlertLabel"></asp:Label>

    <div style="text-align:center;">
    <table class="table table-striped mt-5" style="background-color:#b6d1d4" id="">
  
          <asp:GridView ID="GridViewCarrito" runat="server"  AutoGenerateColumns="False" Width="505px" AutoGenerateDeleteButton="true" OnRowDeleting="GridViewCarrito_RowDeleting" >
                    <Columns>
                        <asp:BoundField HeaderText="Fila" DataField="Fila" ></asp:BoundField>
                        <asp:BoundField HeaderText="Codigo" DataField="Codigo" ></asp:BoundField>
                        <asp:BoundField DataField="Nombre" HeaderText="Nombre" AccessibleHeaderText="True" />
                        <asp:TemplateField AccessibleHeaderText="true" HeaderText="Cantidad"> <ItemTemplate><asp:TextBox type="number" min="0" ID="TextCant" Text='<%# Eval("Cantidad") %>' class="cantidad" runat="server"></asp:TextBox></ItemTemplate></asp:TemplateField>
                        <asp:BoundField DataField="Precio" HeaderText="Precio Unitario" />  
                        <asp:BoundField DataField="Subtotal" HeaderText="Subtotal"/> 
                        <asp:TemplateField AccessibleHeaderText="true" HeaderText="Imagen"> <ItemTemplate > <img src='<%# Eval("Imagen") %>' alt="" /> </ItemTemplate></asp:TemplateField>
                        <asp:TemplateField><ItemTemplate><asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" 
                        ControlToValidate="TextCant" Visible="false"
                        ValidationExpression="/^[0-9]$/"></asp:RegularExpressionValidator></ItemTemplate></asp:TemplateField>
                    </Columns>

              

                </asp:GridView>
        <asp:Button runat="server" ID="ActualizarButton" OnClick="ActualizarButton_Click1" Text="Actualizar carro"/>

        <asp:Label runat="server" ID="LabelTotalProductos" ></asp:Label>
        <asp:Label runat="server" ID="LabelTotalPedido"></asp:Label>
        <asp:Button runat="server" ID="ProductosButton" Text="Agregar productos" OnClientClick="window.open('Productos.aspx')" ></asp:Button>
  </table>
        </div>
        </div>
     
    
</asp:Content>

<%--<asp:Image Height="300px" Width="200px" ID="Imagen" ImageUrl='<%# Eval("Imagen") %>' runat="server"></asp:Image>--%>