<%@ Page Title="CompraRapida" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CompraRapida.aspx.cs" Inherits="WebGalpon.CompraRapida" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <link href="CSS/ayoristas.css" rel="Stylesheet" type="text/css" />

        <div style="margin:50px 0 30px 0;text-align:center">
      <h1> Carrito de tu pedido  </h1> 
      </div>
    
    <div style="text-align:center;">
    <table class="table table-striped mt-5" style="background-color:#b6d1d4" id="">
  
          <asp:GridView ID="GridView1" runat="server"  AutoGenerateColumns="False"
                    Width="505px" OnRowCommand="GridView1_RowCommand" OnRowDeleting="GridView1_RowDeleting" AutoGenerateDeleteButton="true" >
                    <Columns>
                        
                        <asp:BoundField HeaderText="Fila" DataField="Fila" ></asp:BoundField>
                        
                        <asp:TemplateField AccessibleHeaderText="true" HeaderText="Codigo"> <ItemTemplate><asp:TextBox ID="TextCodigo" Text='<%# Eval("Codigo") %>' class="codigo" runat="server"></asp:TextBox></ItemTemplate></asp:TemplateField>
                        
                        <asp:BoundField DataField="Nombre" HeaderText="Nombre" AccessibleHeaderText="True" />
                        
                        
                        <asp:TemplateField AccessibleHeaderText="true" HeaderText="Cantidad"> <ItemTemplate><asp:TextBox type="number" min="0" ID="TextCant" Text='<%# Eval("Cantidad") %>' class="cantidad" runat="server"></asp:TextBox></ItemTemplate></asp:TemplateField>
                       
                        
                        
                        <asp:BoundField DataField="Precio" HeaderText="Precio Unitario" />  
                       
                        <asp:BoundField  DataField="Subtotal" HeaderText="Subtotal"/>

                        <asp:TemplateField><ItemTemplate><asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" 
                        ControlToValidate="TextCant" Visible="false"
                        ValidationExpression="/^[0-9]$/"></asp:RegularExpressionValidator></ItemTemplate></asp:TemplateField> 
                    </Columns>
                </asp:GridView>
        <asp:Button ID="ActualizarButton" runat="server" CssClass="btn btn-dark" Text="Actualizar" OnClick="ActualizarButton_Click"/>
        <asp:Button ID="AgregarFilaButton" runat="server" CssClass="btn btn-dark" Text="AgregarFila" OnClick="AgregarFilaButton_Click"/>
        <asp:Button ID="Agregar10FilasButton" runat="server" CssClass="btn btn-dark" Text="Agregar 10 Filas" OnClick="Agregar10FilasButton_Click"/>
        <asp:Label runat="server" ID="LabelTotalProductos"></asp:Label>
        <asp:Label runat="server" ID="LabelTotalPedido"></asp:Label>
  </table>
        </div>

    

    

    <div style="text-align:center;align-content:center;align-items:center;margin-top:40px">
        <asp:Button runat="server" Text="Imprimir pedido en pdf" id="PdfButton" OnClick="PdfButton_Click" CssClass="btn btn-dark" />
    <asp:Button runat="server" ID="EmailButton" Text="Enviarnos email con tu pedido" OnClick="EmailButton_Click" CssClass="btn btn-dark" />
    <asp:Button runat="server" Text="Necesito ayuda para hacer el pedido" CssClass="btn btn-danger" /> </div>

    <asp:TextBox runat="server" ID="TextMail" TextMode="Email" > </asp:TextBox>
    
  <script type="text/javascript">

      function asignarPrecio(control, precio, seleccionado) {
          if (seleccionado) {
              control.value = precio;
              control.disabled = false;
          } else {
              control.value = '';
              control.disabled = true;
          }
      }

  </script>

</asp:Content>

<%--<%for (int i = 0; i < 10; i++)
            {%>
            
          <tr>
      <th scope="row"> <%=i+1%> </th>
      <td> <asp:TextBox runat="server" ID="TextoCodigo" OnTextChanged="TextoCodigo_TextChanged" ></asp:TextBox></td> 
      <td> <asp:Label runat="server" ID="LabelNombre"></asp:Label> </td>
      <td> <asp:TextBox runat="server" ID="TextoCantidad" OnTextChanged="TextoCantidad_TextChanged" > </asp:TextBox></td>
      <td> <asp:Label runat="server" ID="LabelPrecio"></asp:Label></td> 
      <td> <asp:Label runat="server" ID="LabelSubtotal"></asp:Label></td>
      <td> <asp:ImageButton runat="server" Visible="false" CssClass="BotonEliminar"/> <img src="https://i.ibb.co/VQrL8FP/png-transparent-icon-design-trash-red-line-area-material-rectangle-removebg-preview.png" style="height:40px" /></td>
     
          </tr>


          <%  }%>--%>

<%-- <%for (int i = 0; i < 10; i++)
            {%>
            
          <tr>
      <th scope="row"> <%=i+1%> </th>
      <td> <input type="text" id="inputName" required minlength="4" maxlength="12" size="15" > </td> 
      <td> <textbox id="nombre<%=i %>"></textbox></td>
      <td> <input type="text" id="inputCant<%=i %>" required minlength="4" maxlength="12" size="15"></td>    
      <td> <textbox id="precio<%=i %>"></textbox></td> 
      <td> <textbox id="subtotal<%=i %>"></textbox></td>
      <td> <asp:ImageButton runat="server" Visible="false" CssClass="BotonEliminar" OnClick="Unnamed_Click"/> <img src="https://i.ibb.co/VQrL8FP/png-transparent-icon-design-trash-red-line-area-material-rectangle-removebg-preview.png" style="height:40px" /></td>
      
          </tr>


          <%  }%>--%>